"use client"

import { useEffect, useRef } from "react"
import { preload } from "react-dom"

export function AboutShowreel() {
  const videoRef = useRef<HTMLVideoElement>(null)

  // The poster is the page's LCP element — ask the browser to fetch it
  // with top priority straight from the initial HTML.
  preload("/promo_poster.jpg", { as: "image", fetchPriority: "high" })

  // The promo file is huge (~95MB), so it must not compete with the initial
  // render: preload="none" + no autoplay attribute means nothing is fetched
  // until we call play() after the window "load" event. The src stays in the
  // server HTML so no attribute mutation invalidates the painted poster.
  useEffect(() => {
    const start = () => {
      videoRef.current?.play().catch(() => {})
    }
    if (document.readyState === "complete") {
      start()
      return
    }
    window.addEventListener("load", start, { once: true })
    return () => window.removeEventListener("load", start)
  }, [])

  return (
    <div className="premium-card relative overflow-hidden rounded-[34px]">
      <div className="absolute inset-0 z-10 bg-gradient-to-b from-background/10 via-transparent to-background/40" />
      <div className="relative aspect-video overflow-hidden">
        {/* The poster lives in a plain <img> UNDER the video: a video element
            paints its own poster only after the media player initializes,
            which under main-thread load lands seconds later and tanks LCP.
            The <video> is transparent until playback, so this image shows
            through, then real frames cover it. Poster file generated by
            scripts/generate-promo-poster.mjs — regenerate when the video
            changes. */}
        <img
          src="/promo_poster.jpg"
          alt=""
          aria-hidden
          fetchPriority="high"
          className="absolute inset-0 h-full w-full object-cover"
        />
        <video
          ref={videoRef}
          className="relative h-full w-full object-cover"
          src="/promo_video.mp4"
          muted
          loop
          playsInline
          preload="none"
          controls
          controlsList="nodownload"
          onContextMenu={(event) => event.preventDefault()}
        />
      </div>
    </div>
  )
}
