"use client"

import { useI18n, type Lang } from "@/components/account/i18n"

export const adminDict = {
  ru: {
    // common
    all: "Все",
    live: "Опубл.",
    draft: "Черновик",
    drafts: "Черновики",
    videos: "Видео",
    ideas: "Идеи",
    people: "Люди",
    admins: "Админы",
    members: "Участники",
    suspended: "Заблокирован",
    active: "Активен",
    untitled: "Без названия",
    uncategorized: "Без категории",
    viewAll: "Все",
    manage: "Управлять",
    new: "Новое",
    edit: "Изменить",
    delete: "Удалить",
    publish: "Опубликовать",
    unpublish: "Снять с публикации",
    moveUp: "Выше",
    moveDown: "Ниже",
    actions: "Действия",
    confirm: "Подтвердить",
    cancel: "Отмена",
    saveChanges: "Сохранить",
    search: "Поиск…",
    loading: "Загрузка…",
    refresh: "Обновить",
    you: "Вы",
    admin: "Админ",
    member: "Участник",
    signOut: "Выйти",
    openNav: "Открыть меню",
    adminNav: "Навигация админки",
    breadcrumb: "Навигация",
    noThumbnail: "Нет превью",
    counting: "Подсчёт…",
    unknown: "Неизвестно",
    done: "Готово",
    name: "Имя",
    description: "Описание",
    title: "Заголовок",
    type: "Тип",
    video: "Видео",
    idea: "Идея",
    role: "Роль",
    status: "Статус",
    password: "Пароль",
    email: "Email",
    fullName: "Полное имя",
    optional: "необязательно",
    creating: "Создание…",
    updating: "Обновление…",
    online: "В сети",
    offline: "Не в сети",
    idle: "ожидание",
    busy: "занят",
    error: "ошибка",

    // overview quick actions
    qaAddVideo: "Добавить видео",
    qaAddVideoDesc: "Загрузите медиа и опубликуйте за секунды",
    qaCaptureIdea: "Сохранить идею",
    qaCaptureIdeaDesc: "Зафиксируйте концепт, пока он не исчез",
    qaManagePeople: "Управление людьми",
    qaManagePeopleDesc: "Админы и контроль доступа",

    // overview stats
    liveDraftsHint: "{live} опубл. · {drafts} черновиков",
    activeSuspendedHint: "{active} активных · {suspended} заблок.",
    privilegedAccounts: "Привилегированные аккаунты",

    // overview recent videos
    showcase: "Витрина",
    recentVideos: "Недавние видео",
    noVideosYet: "Пока нет видео",
    noVideosYetDesc: "Добавьте первое видео, чтобы на сайте было что показать.",
    addVideo: "Добавить видео",

    // overview recent ideas
    inspiration: "Вдохновение",
    latestIdeas: "Последние идеи",
    noIdeasYet: "Пока нет идей",
    noIdeasYetDesc: "Сохраняйте идеи, чтобы они не потерялись.",
    addIdea: "Добавить идею",

    // overview team
    newestAccounts: "Новые аккаунты",
    noPeopleYet: "Пока никого нет",
    noPeopleYetDesc: "Когда появятся пользователи, они отобразятся здесь.",

    // content
    searchContent: "Поиск по видео и идеям…",
    nothingHereYet: "Пока пусто",
    nothingMatches: "Ничего не найдено",
    contentEmptyDesc: "Добавьте первое видео или идею в библиотеку.",
    contentNoMatchDesc: "Попробуйте другой поиск или снимите фильтры.",
    categories: "Категории",

    // people / users
    searchPeople: "Поиск по имени или email…",
    peopleEmptyDesc: "Когда появятся пользователи, они отобразятся здесь.",
    peopleNoMatchDesc: "Попробуйте другой поиск или фильтр.",
    filterAdmins: "Админы",
    filterMembers: "Участники",
    filterSuspended: "Заблокированы",
    newPerson: "Новый пользователь",
    editPerson: "Редактировать",
    createAccount: "Создать аккаунт",
    provisionDesc: "Создайте аккаунт, чтобы человек мог сразу войти.",
    editUserDesc: "Обновите профиль, пароль или права доступа.",
    namePlaceholder: "Анна Петрова",
    emailPlaceholder: "anna@example.com",
    newPasswordKeep: "Новый пароль (оставьте пустым, чтобы не менять)",
    passwordMin: "Не меньше 8 символов",
    hidePassword: "Скрыть пароль",
    showPassword: "Показать пароль",
    cantDemoteSelf: "Нельзя снять права с себя.",
    cantSuspendSelf: "Нельзя заблокировать себя.",
    joinedPrefix: "С ",
    editProfile: "Редактировать профиль",
    removeAdmin: "Снять админа",
    makeAdmin: "Сделать админом",
    suspend: "Заблокировать",
    reactivate: "Разблокировать",
    deleteAccount: "Удалить аккаунт",
    errFullName: "Введите полное имя (не меньше 2 символов).",
    errEmail: "Введите корректный email.",
    errPassword: "Пароль должен быть не меньше 8 символов.",
    errNewPassword: "Новый пароль должен быть не меньше 8 символов.",

    // visitors
    audienceAll: "Все",
    audienceSignedIn: "Авторизованные",
    audienceAnonymous: "Анонимные",
    window24h: "24ч",
    window7d: "7д",
    window30d: "30д",
    windowAll: "Всё время",
    viewVisitors: "Посетители",
    viewEvents: "События",
    audience: "Аудитория",
    window: "Период",
    visitorsLoadError: "Не удалось загрузить данные посетителей.",
    visits24h: "Визиты • 24ч",
    unique24h: "Уникальные • 24ч",
    uniqueHint: "Уникальные отпечатки",
    signedIn24h: "Авторизованные • 24ч",
    signedInHint: "Уникальные аккаунты",
    visits7d: "Визиты • 7д",
    uniqueCount: "{n} уникальных",
    searchVisitors: "Поиск по email, имени, пути или fingerprint…",
    noVisitorsWindow: "Нет посетителей за этот период",
    noVisitorsWindowDesc: "Расширьте период или сбросьте фильтры.",
    noEventsWindow: "Нет событий за этот период",
    noEventsWindowDesc: "Когда откроют публичную страницу — появятся здесь.",
    signedInUser: "Авторизованный",
    anonymous: "Аноним",
    signedIn: "В системе",
    visits: "Визиты",
    pages: "Страницы",
    lastSeen: "Был",
    lastOn: "Последний: ",
    topPages7d: "Топ страниц • 7д",
    noPagesTracked: "Страницы ещё не отслеживаются.",
    timeAgoS: "{n}с назад",
    timeAgoM: "{n}м назад",
    timeAgoH: "{n}ч назад",
    timeAgoD: "{n}д назад",

    // remote access
    remoteLoadError: "Не удалось загрузить список.",
    remoteRevokeError: "Не удалось отключить.",
    remoteRevoked: "Компьютер отключён.",
    remoteRevokeTitle: "Отключить компьютер?",
    remoteRevokeDesc:
      "«{name}» больше не сможет обращаться к API. Токен будет отозван.",
    remoteRevokeConfirm: "Отключить",
    remoteProject: "Проект: {name}",
    remoteNoProject: "Нет активного проекта",
    remoteHeartbeat: "Сигнал ",
    remoteRotateToken: "Обновить токен",
    remoteNameRequired: "Укажите имя компьютера.",
    remoteCreateError: "Не удалось создать компьютер.",
    remoteCreated: "Компьютер подключён.",
    remoteTokenCopied: "Токен скопирован.",
    remoteTokenCopyError: "Не удалось скопировать токен.",
    remoteTokenTitle: "Токен компьютера",
    remoteConnectTitle: "Подключить компьютер",
    remoteTokenSaveNow: "Сохраните токен сейчас — он больше не будет показан.",
    remoteConnectDesc: "Создайте запись для удалённой машины автоматизации.",
    remoteBearerToken: "Токен",
    remoteNamePlaceholder: "render-box-1",
    remoteDescOptional: "Описание (необязательно)",
    remoteDescPlaceholder: "Студия, GPU…",
    remoteConnect: "Подключить",
    remoteRotateError: "Не удалось обновить токен.",
    remoteRotated: "Новый токен создан. Старый больше не действует.",
    remoteNewToken: "Новый токен",
    remoteRotateTitle: "Обновить токен?",
    remoteRotateTokenFor: "Токен для «{name}». Сохраните его сейчас.",
    remoteRotateWarnFor: "Старый токен для «{name}» сразу перестанет работать.",
    remoteRotateWarn: "Старый токен сразу перестанет работать.",
    remoteTabComputers: "Компьютеры",
    remoteTabApi: "API",
    remoteApiCopy: "Копировать",
    remoteApiCopied: "Скопировано.",
    remoteApiCopyError: "Не удалось скопировать.",
    remoteApiSingleEndpoint: "Единственная точка входа для внешних машин.",
    remoteApiStep: "Шаг",
    remoteApiStepAuth: "Проверка token",
    remoteApiStepProps: "Валидация props",
    remoteApiStepRun: "Выполнение action",
    remoteApiEnvelope: "Тело запроса",
    remoteApiErrors: "Ошибки",
    remoteApiGroupComputer: "Компьютер",
    remoteApiGroupStorage: "Файлы",
    remoteApiProp: "Поле",
    remoteApiRequired: "Обяз.",
    remoteApiRequiredYes: "да",
    remoteApiNoProps: "props не требуются — передайте {} или опустите поле.",
    remoteApiExample: "Пример запроса",
    remoteApiResponse: "Пример ответа",

    // content dialog
    newContent: "Новый контент",
    editVideo: "Редактировать видео",
    editIdea: "Редактировать идею",
    publishVideo: "Опубликовать видео",
    publishIdea: "Опубликовать идею",
    errTitle: "Добавьте заголовок.",
    errTags: "Добавьте хотя бы один тег.",
    errThumbnail: "Загрузите изображение превью.",
    errVideoFile: "Загрузите видеофайл.",
    errDescription: "Добавьте описание.",
    contentDialogDesc:
      "Медиа, текст и метаданные. Всё сразу обновляет сайт.",
    switchTypeWarn:
      "Смена типа создаст новую запись — у неё будет новый id.",
    thumbnail: "Превью",
    thumbnailOptional: "Превью (необязательно)",
    thumbnailHintVideo: "Показывается в сетке видео",
    thumbnailHintIdea: "Делает карточку заметнее",
    videoFile: "Видеофайл",
    videoFileOptional: "Видеофайл (необязательно)",
    videoFileHint: "Воспроизводится на странице",
    videoFileHintIdea: "Прикрепите клип, если есть",
    titlePlaceholder: "Короткий понятный заголовок",
    tags: "Теги",
    tagsPlaceholder: "Выберите или введите теги…",
    duration: "Длительность",
    durationOptional: "Длительность (необязательно)",
    durationHint: "Авто из файла (можно править)",
    descriptionPlaceholder: "О чём это?",

    // media dropzone
    errImageType: "Выберите изображение JPG, PNG, WEBP или GIF.",
    errVideoType: "Выберите видео MP4, WEBM или MOV.",
    uploadingImage: "Загрузка изображения…",
    uploadingVideo: "Загрузка видео…",
    uploadComplete: "Загрузка завершена",
    uploadCancelled: "Загрузка отменена.",
    uploadFailed: "Не удалось загрузить. Попробуйте ещё раз.",
    uploadPrepareError: "Не удалось подготовить загрузку (HTTP {status}).",
    uploadNoPublicUrl: "Сервер не вернул публичный URL загруженного объекта.",
    uploadStorageRejected: "Хранилище отклонило загрузку (HTTP {status}).",
    preview: "Превью",
    replace: "Заменить",
    remove: "Удалить",
    uploadingPercent: "Загрузка {percent}%",
    uploadingEllipsis: "Загрузка…",
    dragImage: "Перетащите изображение или нажмите для выбора",
    dragVideo: "Перетащите видео или нажмите для выбора",
    imageFormats: "JPG, PNG, WEBP, GIF",
    videoFormats: "MP4, WEBM, MOV",

    // data context toasts / confirms
    loadAdminError: "Не удалось загрузить данные админки. Обновите страницу.",
    switchTypeError: "Не удалось сменить тип. Исходная запись без изменений.",
    convertPartialError:
      "Новая запись создана, но старую удалить не удалось. Удалите вручную.",
    convertedToVideo: "Преобразовано в видео.",
    convertedToIdea: "Преобразовано в идею.",
    saveError: "Не удалось сохранить изменения.",
    addError: "Не удалось добавить {kind}.",
    videoUpdated: "Видео обновлено.",
    ideaUpdated: "Идея обновлена.",
    videoAdded: "Видео добавлено.",
    ideaAdded: "Идея добавлена.",
    videoUpdateError: "Не удалось обновить видео.",
    ideaUpdateError: "Не удалось обновить идею.",
    reorderError: "Не удалось изменить порядок.",
    deleteError: "Не удалось удалить.",
    videoDeleted: "Видео удалено.",
    ideaDeleted: "Идея удалена.",
    passwordRequired: "Пароль обязателен.",
    userSaveError: "Не удалось сохранить пользователя.",
    userCreateError: "Не удалось создать пользователя.",
    userUpdated: "Пользователь обновлён.",
    userCreated: "Пользователь создан.",
    userUpdateError: "Не удалось обновить пользователя.",
    userDeleteError: "Не удалось удалить пользователя.",
    userDeleted: "Пользователь удалён.",
    deleteVideoTitle: "Удалить это видео?",
    deleteVideoDesc: "«{title}» будет удалено безвозвратно.",
    deleteVideoConfirm: "Удалить видео",
    deleteIdeaTitle: "Удалить эту идею?",
    deleteIdeaDesc: "«{title}» будет удалена безвозвратно.",
    deleteIdeaConfirm: "Удалить идею",
    deleteUserTitle: "Удалить этот аккаунт?",
    deleteUserDesc: "{name} сразу потеряет доступ.",
    deleteUserConfirm: "Удалить аккаунт",
    kindVideo: "видео",
    kindIdea: "идею",
  },
  en: {
    all: "All",
    live: "Live",
    draft: "Draft",
    drafts: "Drafts",
    videos: "Videos",
    ideas: "Ideas",
    people: "People",
    admins: "Admins",
    members: "Members",
    suspended: "Suspended",
    active: "Active",
    untitled: "Untitled",
    uncategorized: "Uncategorized",
    viewAll: "View all",
    manage: "Manage",
    new: "New",
    edit: "Edit",
    delete: "Delete",
    publish: "Publish",
    unpublish: "Unpublish",
    moveUp: "Move up",
    moveDown: "Move down",
    actions: "Actions",
    confirm: "Confirm",
    cancel: "Cancel",
    saveChanges: "Save changes",
    search: "Search…",
    loading: "Loading…",
    refresh: "Refresh",
    you: "You",
    admin: "Admin",
    member: "Member",
    signOut: "Sign out",
    openNav: "Open navigation",
    adminNav: "Admin navigation",
    breadcrumb: "Breadcrumb",
    noThumbnail: "No thumbnail",
    counting: "Counting…",
    unknown: "Unknown",
    done: "Done",
    name: "Name",
    description: "Description",
    title: "Title",
    type: "Type",
    video: "Video",
    idea: "Idea",
    role: "Role",
    status: "Status",
    password: "Password",
    email: "Email",
    fullName: "Full name",
    optional: "optional",
    creating: "Creating…",
    updating: "Updating…",
    online: "Online",
    offline: "Offline",
    idle: "idle",
    busy: "busy",
    error: "error",

    qaAddVideo: "Add a new video",
    qaAddVideoDesc: "Upload media and publish in seconds",
    qaCaptureIdea: "Capture an idea",
    qaCaptureIdeaDesc: "Park a concept before it disappears",
    qaManagePeople: "Manage people",
    qaManagePeopleDesc: "Promote admins & control access",

    liveDraftsHint: "{live} live · {drafts} drafts",
    activeSuspendedHint: "{active} active · {suspended} suspended",
    privilegedAccounts: "Privileged accounts",

    showcase: "Showcase",
    recentVideos: "Recent videos",
    noVideosYet: "No videos yet",
    noVideosYetDesc: "Add your first video so the homepage has something to show.",
    addVideo: "Add a video",

    inspiration: "Inspiration",
    latestIdeas: "Latest ideas",
    noIdeasYet: "No ideas yet",
    noIdeasYetDesc: "Capture sparks of inspiration so they don't get lost.",
    addIdea: "Add an idea",

    newestAccounts: "Newest accounts",
    noPeopleYet: "No people yet",
    noPeopleYetDesc: "Once people sign up they'll appear here.",

    searchContent: "Search across videos and ideas…",
    nothingHereYet: "Nothing here yet",
    nothingMatches: "Nothing matches",
    contentEmptyDesc: "Add your first video or idea to fill the library.",
    contentNoMatchDesc: "Try a different search or relax the filters.",
    categories: "Categories",

    searchPeople: "Search by name or email…",
    peopleEmptyDesc: "Once people sign up they will appear here.",
    peopleNoMatchDesc: "Try a different search term or filter.",
    filterAdmins: "Admins",
    filterMembers: "Members",
    filterSuspended: "Suspended",
    newPerson: "New person",
    editPerson: "Edit person",
    createAccount: "Create account",
    provisionDesc: "Provision an account so this person can sign in immediately.",
    editUserDesc: "Update the profile, rotate the password or change permissions.",
    namePlaceholder: "Anna Petrova",
    emailPlaceholder: "anna@example.com",
    newPasswordKeep: "New password (leave blank to keep)",
    passwordMin: "At least 8 characters",
    hidePassword: "Hide password",
    showPassword: "Show password",
    cantDemoteSelf: "You can't demote yourself.",
    cantSuspendSelf: "You can't suspend yourself.",
    joinedPrefix: "Joined ",
    editProfile: "Edit profile",
    removeAdmin: "Remove admin",
    makeAdmin: "Make admin",
    suspend: "Suspend",
    reactivate: "Reactivate",
    deleteAccount: "Delete account",
    errFullName: "Please enter a full name (at least 2 characters).",
    errEmail: "Please enter a valid email address.",
    errPassword: "Password must be at least 8 characters.",
    errNewPassword: "New password must be at least 8 characters.",

    audienceAll: "All",
    audienceSignedIn: "Signed in",
    audienceAnonymous: "Anonymous",
    window24h: "24h",
    window7d: "7d",
    window30d: "30d",
    windowAll: "All time",
    viewVisitors: "Visitors",
    viewEvents: "Events",
    audience: "Audience",
    window: "Window",
    visitorsLoadError: "Could not load visitors data.",
    visits24h: "Visits • 24h",
    unique24h: "Unique • 24h",
    uniqueHint: "Distinct fingerprints",
    signedIn24h: "Signed in • 24h",
    signedInHint: "Distinct user accounts",
    visits7d: "Visits • 7d",
    uniqueCount: "{n} unique",
    searchVisitors: "Search by email, name, path or fingerprint…",
    noVisitorsWindow: "No visitors in this window",
    noVisitorsWindowDesc: "Try widening the time range or clearing filters.",
    noEventsWindow: "No events in this window",
    noEventsWindowDesc: "Once people open a public page they'll show up here.",
    signedInUser: "Signed-in user",
    anonymous: "Anonymous",
    signedIn: "Signed in",
    visits: "Visits",
    pages: "Pages",
    lastSeen: "Last seen",
    lastOn: "Last on ",
    topPages7d: "Top pages • 7d",
    noPagesTracked: "No pages tracked yet.",
    timeAgoS: "{n}s ago",
    timeAgoM: "{n}m ago",
    timeAgoH: "{n}h ago",
    timeAgoD: "{n}d ago",

    remoteLoadError: "Could not load the list.",
    remoteRevokeError: "Could not disconnect.",
    remoteRevoked: "Computer disconnected.",
    remoteRevokeTitle: "Disconnect computer?",
    remoteRevokeDesc:
      "“{name}” will no longer be able to call the API. The token will be revoked.",
    remoteRevokeConfirm: "Disconnect",
    remoteProject: "Project: {name}",
    remoteNoProject: "No active project",
    remoteHeartbeat: "Heartbeat ",
    remoteRotateToken: "Rotate token",
    remoteNameRequired: "Enter a computer name.",
    remoteCreateError: "Could not create the computer.",
    remoteCreated: "Computer connected.",
    remoteTokenCopied: "Token copied.",
    remoteTokenCopyError: "Could not copy the token.",
    remoteTokenTitle: "Computer token",
    remoteConnectTitle: "Connect computer",
    remoteTokenSaveNow: "Save the token now — it won’t be shown again.",
    remoteConnectDesc: "Create a record for a remote automation machine.",
    remoteBearerToken: "Token",
    remoteNamePlaceholder: "render-box-1",
    remoteDescOptional: "Description (optional)",
    remoteDescPlaceholder: "Studio, GPU…",
    remoteConnect: "Connect",
    remoteRotateError: "Could not rotate the token.",
    remoteRotated: "New token created. The old one no longer works.",
    remoteNewToken: "New token",
    remoteRotateTitle: "Rotate token?",
    remoteRotateTokenFor: "Token for “{name}”. Save it now.",
    remoteRotateWarnFor: "The old token for “{name}” will stop working immediately.",
    remoteRotateWarn: "The old token will stop working immediately.",
    remoteTabComputers: "Computers",
    remoteTabApi: "API",
    remoteApiCopy: "Copy",
    remoteApiCopied: "Copied.",
    remoteApiCopyError: "Could not copy.",
    remoteApiSingleEndpoint: "The only entry point for external machines.",
    remoteApiStep: "Step",
    remoteApiStepAuth: "Validate token",
    remoteApiStepProps: "Validate props",
    remoteApiStepRun: "Run action",
    remoteApiEnvelope: "Request body",
    remoteApiErrors: "Errors",
    remoteApiGroupComputer: "Computer",
    remoteApiGroupStorage: "Files",
    remoteApiProp: "Field",
    remoteApiRequired: "Req.",
    remoteApiRequiredYes: "yes",
    remoteApiNoProps: "No props required — send {} or omit the field.",
    remoteApiExample: "Example request",
    remoteApiResponse: "Example response",

    newContent: "New content",
    editVideo: "Edit video",
    editIdea: "Edit idea",
    publishVideo: "Publish video",
    publishIdea: "Publish idea",
    errTitle: "Please add a title.",
    errTags: "Please add at least one tag.",
    errThumbnail: "Please upload a thumbnail image.",
    errVideoFile: "Please upload the video file.",
    errDescription: "Please add a description.",
    contentDialogDesc:
      "Configure media, copy and metadata. Everything updates the live site.",
    switchTypeWarn:
      "Switching type will recreate this content under the new kind — the record will get a new id.",
    thumbnail: "Thumbnail",
    thumbnailOptional: "Thumbnail (optional)",
    thumbnailHintVideo: "Shown in the video grid",
    thumbnailHintIdea: "Helps cards stand out",
    videoFile: "Video file",
    videoFileOptional: "Video file (optional)",
    videoFileHint: "Plays on the detail page",
    videoFileHintIdea: "Attach a clip if you have one",
    titlePlaceholder: "A short, descriptive title",
    tags: "Tags",
    tagsPlaceholder: "Select or type tags…",
    duration: "Duration",
    durationOptional: "Duration (optional)",
    durationHint: "Auto from video file (editable)",
    descriptionPlaceholder: "What is this about?",

    errImageType: "Please pick a JPG, PNG, WEBP or GIF image.",
    errVideoType: "Please pick an MP4, WEBM or MOV video.",
    uploadingImage: "Uploading image…",
    uploadingVideo: "Uploading video…",
    uploadComplete: "Upload complete",
    uploadCancelled: "Upload was cancelled.",
    uploadFailed: "Upload failed. Please try again.",
    uploadPrepareError: "Could not prepare upload (HTTP {status}).",
    uploadNoPublicUrl: "Server did not return a public URL for the uploaded object.",
    uploadStorageRejected: "Storage rejected the upload (HTTP {status}).",
    preview: "Preview",
    replace: "Replace",
    remove: "Remove",
    uploadingPercent: "Uploading {percent}%",
    uploadingEllipsis: "Uploading…",
    dragImage: "Drag an image here, or click to browse",
    dragVideo: "Drag a video here, or click to browse",
    imageFormats: "JPG, PNG, WEBP, GIF",
    videoFormats: "MP4, WEBM, MOV",

    loadAdminError: "Could not load admin data. Please refresh.",
    switchTypeError: "Could not switch type. Original is unchanged.",
    convertPartialError:
      "New record created, but couldn't remove the old one. Delete it manually.",
    convertedToVideo: "Converted to video.",
    convertedToIdea: "Converted to idea.",
    saveError: "Could not save changes.",
    addError: "Could not add {kind}.",
    videoUpdated: "Video updated.",
    ideaUpdated: "Idea updated.",
    videoAdded: "Video added.",
    ideaAdded: "Idea added.",
    videoUpdateError: "Could not update the video.",
    ideaUpdateError: "Could not update the idea.",
    reorderError: "Could not change the order.",
    deleteError: "Could not delete.",
    videoDeleted: "Video deleted.",
    ideaDeleted: "Idea deleted.",
    passwordRequired: "Password is required.",
    userSaveError: "Could not save the user.",
    userCreateError: "Could not create the user.",
    userUpdated: "User updated.",
    userCreated: "User created.",
    userUpdateError: "Could not update the user.",
    userDeleteError: "Could not delete the user.",
    userDeleted: "User deleted.",
    deleteVideoTitle: "Delete this video?",
    deleteVideoDesc: "“{title}” will be removed permanently.",
    deleteVideoConfirm: "Delete video",
    deleteIdeaTitle: "Delete this idea?",
    deleteIdeaDesc: "“{title}” will be removed permanently.",
    deleteIdeaConfirm: "Delete idea",
    deleteUserTitle: "Delete this account?",
    deleteUserDesc: "{name} will lose access immediately.",
    deleteUserConfirm: "Delete account",
    kindVideo: "video",
    kindIdea: "idea",
  },
} as const

export type AdminDict = (typeof adminDict)[Lang]
export type AdminDictKey = keyof AdminDict

export function tf(
  template: string,
  vars: Record<string, string | number>,
): string {
  return template.replace(/\{(\w+)\}/g, (_, key: string) =>
    String(vars[key] ?? ""),
  )
}

export function useAdminI18n() {
  const { lang } = useI18n()
  return adminDict[lang]
}
